name: checkpoint_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  flutter_svg: ^2.0.10+1
  animate_do: ^3.1.2
  dio: ^5.3.3
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  get_storage: ^2.1.1
  flutter_spinkit: ^5.2.0
  #flutter_launcher_icons: ^0.14.3
  form_field_validator: ^1.1.0
  http: ^1.1.0
  geolocator: ^11.1.0
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  flutter_local_notifications: ^19.2.1
  audioplayers: ^5.2.1
  flutter_sound: ^9.2.13
  dart_pusher_channels: ^1.2.2+1
  permission_handler: ^11.0.1
  path: any
  http_parser: any
  qr_code_scanner_plus: ^2.0.10+1
  #flutter_native_splash: ^2.4.4
  dotted_border: ^2.1.0
  chat_bubbles: ^1.7.0
  google_mlkit_face_detection: ^0.13.1
  image: ^3.3.0
  tflite_flutter: ^0.11.0
  camera: ^0.11.1
  provider: ^6.1.5
  mobile_scanner: ^7.0.0
  image_picker: ^1.1.2
  screen_brightness: ^2.1.3
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_tts: ^4.2.2
  awesome_notifications: ^0.10.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  battery_plus: ^6.2.2
  package_info_plus: ^8.3.0
  install_plugin: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/sounds/
    - assets/models/facenet.tflite

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches/Staatliches-Regular.ttf
